# Generated by Django 3.2 on 2023-05-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('billdate', models.CharField(max_length=20)),
                ('reciptno', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('feesamount', models.CharField(max_length=100)),
                ('paytype', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
