# Generated by Django 3.2 on 2023-05-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('feesamount', models.CharField(max_length=100)),
                ('paytype', models.CharField(max_length=100)),
            ],
        ),
    ]
